import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { CodePanel } from "@/features/code-explorer/ui/code-panel";
import { findPublishedProject, publishedProjects } from "@/entities/project/model/projects";

export function generateStaticParams() { return publishedProjects.map((project) => ({ slug: project.slug })); }
export async function generateMetadata({ params }: PageProps<"/projects/[slug]">): Promise<Metadata> { const { slug } = await params; const project = findPublishedProject(slug); return project ? { title: project.title, description: project.summary } : {}; }
export default async function ProjectPage({ params }: PageProps<"/projects/[slug]">) { const { slug } = await params; const project = findPublishedProject(slug); if (!project) notFound(); return <main><section className="project-hero soft-grid"><div className="container"><Link href="/#projects" className="back-link">← Все проекты</Link><div className="project-title"><div><p className="eyebrow">{project.category}</p><h1>{project.title}</h1></div><span>{project.year}</span></div><p className="project-summary">{project.summary}</p>{(project.liveUrl || project.repoUrl) && <div className="project-actions">{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noreferrer" className="live-link">Открыть сайт ↗</a>}{project.repoUrl && <a href={project.repoUrl} target="_blank" rel="noreferrer" className="repo-link">Репозиторий ↗</a>}</div>}</div></section><section className="container project-body"><div className="detail-grid"><aside><p className="eyebrow">Контекст</p><h2>Задача</h2></aside><p>{project.challenge}</p><aside><p className="eyebrow">Моя роль</p><h2>Личный вклад</h2></aside><ul className="contribution-list">{project.contribution.map((item) => <li key={item}>{item}</li>)}</ul><aside><p className="eyebrow">Итог</p><h2>Результат</h2></aside><p>{project.result}</p></div><section className="stack-section"><p className="eyebrow">Инструменты</p><h2>Стек и решения</h2><div>{project.stack.map((item) => <article key={item.name}><h3>{item.name}</h3><p>{item.note}</p></article>)}</div></section>{project.code && <CodePanel excerpts={project.code} />}</section></main>; }
