import sources from "./source-examples.json";
export type CodeExample = { path:string; language:string; code:string; sourceUrl:string; summary:string; startLine?:number; endLine?:number };
export type ProjectMedia = { src:string; caption:string; type:"image"|"video"; poster?:string };
export type Project = { slug:string; title:string; shortTitle:string; kind:string; year:string; theme:string; summary:string; description:string; role:string; stack:string[]; tasks:string[]; decisions:{title:string;text:string}[]; result:string; repo?:string; demo?:string; repoNote?:string; cover?:string; media:ProjectMedia[]; examples:CodeExample[] };
export const profile={name:"Денис Баркалов",phone:"+7 (918) 546-32-01",phoneHref:"tel:+79185463201",github:"https://github.com/DenissioBarkani"};
export const projects:Project[]=[
 {slug:"tournament-platform",title:"B2B-платформа турниров",shortTitle:"Турниры",kind:"Оплачиваемая разработка",year:"2025 — 2026",theme:"tournament",summary:"Интерфейсы для организации турниров по единоборствам и работы судей.",description:"Разрабатывал клиентскую часть платформы для автоматизации турниров по единоборствам в команде заказчика. Проект одновременно был оплачиваемой работой и моей выпускной квалификационной работой.",role:"Frontend-разработчик · участие в системном анализе",stack:["Vue 3","Nuxt","TypeScript","Tailwind CSS","Vue Query","Pinia","REST API"],tasks:["Разработал адаптивные интерфейсы панели судейства и публичной страницы турнира.","Создал и поддерживал библиотеку из 20+ переиспользуемых UI-компонентов.","Интегрировал клиентскую часть с REST API и настроил запросы через Vue Query.","Исследовал предметную область, участвовал в интервью с заказчиком и подготовке требований.","Предложил переход на Nuxt; после обсуждения команда выбрала его для клиентской части."],decisions:[{title:"Переиспользуемые компоненты",text:"Общие элементы вынесены в библиотеку, чтобы поддерживать единый стиль и собирать новые интерфейсы из готовых компонентов."},{title:"Асинхронные данные",text:"Для REST API использовал Vue Query. Клиентское состояние организовано с помощью Pinia."},{title:"От требований к интерфейсу",text:"Аналитическая работа помогала связывать сценарии организаторов и судей с конкретными страницами и действиями."}],result:"Реализована клиентская часть MVP. По материалам выпускного проекта платформа прошла тестирование на реальном мероприятии.",media:[],examples:[]},
 {slug:"student-profile",title:"Цифровой профиль студента",shortTitle:"Цифровой профиль",kind:"Проект ДГТУ",year:"2025",theme:"student",summary:"Платформа для студентов и компаний на Next.js и React.",description:"Командный проект ДГТУ: клиентская часть платформы для студентов и компаний. Работал над интерфейсами совместно с backend-разработчиком.",role:"Frontend-разработчик · UI/UX",stack:["Next.js","React","TypeScript","Tailwind CSS","REST API"],tasks:["Разработал клиентскую часть с нуля.","Создал адаптивные страницы и переиспользуемые компоненты.","Работал над UI/UX-дизайном интерфейсов.","Подключил тестовый REST API для пользователей и компаний."],decisions:[{title:"Компонентная структура",text:"Повторяющиеся элементы выделены в компоненты. Страницы и маршруты организованы средствами Next.js."},{title:"Совместная работа с backend",text:"Согласовывал клиентские сценарии с backend-разработчиком и подключал API к интерфейсам."}],result:"Реализованы клиентские страницы MVP и взаимодействие с тестовым API.",media:[],examples:[]},
 {slug:"center-invest",title:"Боты под управлением",shortTitle:"Центр-инвест",kind:"Практика · Центр-инвест",year:"Лето 2025",theme:"bank",summary:"Внутреннее SPA для управления Telegram-чат-ботами.",description:"Во время практики в банке «Центр-инвест» работал над интерфейсом управления Telegram-ботами. Задачи были связаны с формами, API, таблицами и состояниями приложения.",role:"Frontend-разработчик · практика",stack:["React","TypeScript","MUI","Zustand","React Hook Form","Zod","REST API"],tasks:["Работал с типизированными формами и валидацией.","Организовал API-слой с Axios Interceptors.","Реализовывал защищённые маршруты и Basic-аутентификацию.","Работал с виртуализированной таблицей, загрузкой и обработкой ошибок.","Добавлял подтверждение удаления и другие состояния интерфейса."],decisions:[{title:"Формы и валидация",text:"Использовал React Hook Form и Zod для обработки ввода и проверки данных."},{title:"Состояния приложения",text:"Предусматривал загрузку, ошибки и подтверждение удаления, чтобы результат действий пользователя был понятен."}],result:"Получил практический опыт разработки внутреннего React-приложения и интеграции с API.",repo:"https://github.com/DenissioBarkani/Center-invest-hr-telegram",repoNote:"Публичный fork Center-invest-IT/hr-telegram-bot-admin. Описание личного вклада — по материалам практики.",media:[],examples:[]},
 {slug:"ai-artdir",title:"AI-Artdir",shortTitle:"AI-Artdir",kind:"Личный проект · вёрстка",year:"2023",theme:"artdir",summary:"Адаптивный лендинг по Figma с формой и слайдером.",description:"Лендинг AI-Artdir: работа с макетом Figma, адаптивной вёрсткой и интерактивными элементами на JavaScript.",role:"Вёрстка и JavaScript",stack:["HTML","Sass","JavaScript","jQuery","Gulp"],tasks:["Сверстал адаптивный лендинг по макету Figma.","Реализовал клиентские состояния формы и валидацию.","Добавил слайдер тарифов.","Работал со сборкой на Gulp."],decisions:[{title:"От макета к странице",text:"Реализовывал структуру и адаптивные состояния интерфейса по Figma."},{title:"Интерактивные элементы",text:"JavaScript управляет навигацией, формой и слайдером. В публичном демо успешная отправка формы имитируется; серверная отправка не подключена."}],result:"Реализован лендинг с адаптивной вёрсткой и клиентскими взаимодействиями.",repo:"https://github.com/DenissioBarkani/Ai-artdir",media:[],examples:[]},
 {slug:"vue-sneakers",title:"Vue Sneakers",shortTitle:"Vue Sneakers",kind:"Учебный проект · по гайду",year:"Vue 3",theme:"sneakers",summary:"Каталог кроссовок: компоненты Vue, поиск и корзина.",description:"Учебный проект, выполненный по гайду. Показывает практику работы с Vue: карточки товаров, корзина, поиск и взаимодействие с API.",role:"Учебная практика Vue",stack:["Vue 3","JavaScript","Tailwind CSS","Axios"],tasks:["Работал с компонентами карточек и списком товаров.","Реализовывал действия корзины.","Работал с поиском и debounce.","Использовал Axios для запросов к API."],decisions:[{title:"Корзина",text:"Состояние корзины и связанные действия передаются компонентам через provide/inject."},{title:"Поиск",text:"Debounce уменьшает количество обновлений при вводе строки поиска."}],result:"Учебное приложение с открытыми исходниками и доступным демо. Самостоятельные изменения относительно гайда отдельно не атрибутированы.",repo:"https://github.com/DenissioBarkani/vue-sneakers",media:[],examples:[]}
];
const sourceMap:Record<string,string>={"student-profile":"DenissioBarkani/student-dep","ai-artdir":"DenissioBarkani/Ai-artdir","vue-sneakers":"DenissioBarkani/vue-sneakers"};
for(const p of projects){const source=(sources as Record<string,{files:CodeExample[];demoUrl:string|null}>)[sourceMap[p.slug]];if(source){p.examples=source.files;if(source.demoUrl)p.demo=source.demoUrl;if(p.slug==="student-profile")p.repoNote="Публичные примеры Next.js взяты из student-dep. Описание командного проекта — по материалам резюме."}}
export function getProject(slug:string){return projects.find(p=>p.slug===slug)}
